services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
      - ./redis.conf:/redis-stack.conf
    environment:
      - REDIS_ARGS=--save 60 1 --appendonly yes --appendfsync everysec --maxmemory 6gb --maxmemory-policy allkeys-lru
      - REDISEARCH_ARGS=MAXPREFIXEXPANSIONS 100 MAXAGGREGATERESULTS 100000
      - REDISJSON_ARGS=MAXMEMORY 1gb
      - REDISTIMESERIES_ARGS=RETENTION_POLICY=20
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      memlock: -1
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G

volumes:
  redis_data:
    driver: local
